In [1]:
import tensorflow as tf


x = tf.Variable(2.0)
with tf.GradientTape() as tape:
    y = 3*x**4
    dy_dx = tape.gradient(y, x)
print(dy_dx)
print(y)

tf.Tensor(96.0, shape=(), dtype=float32)
tf.Tensor(48.0, shape=(), dtype=float32)


In [2]:
x = tf.Variable(2.5)


with tf.GradientTape() as tape:
    y = x**2

print(y)
print(type(tape))

tf.Tensor(6.25, shape=(), dtype=float32)
<class 'tensorflow.python.eager.backprop.GradientTape'>


In [3]:
dy_dx = tape.gradient(y,x)
print(dy_dx.numpy())

5.0


# TENSOR INPUT


In [4]:
# y = x.w + b

w = tf.Variable(tf.random.normal((3, 2)), name = 'w')
print(w)

b = tf.Variable(tf.zeros((1,2), dtype=tf.float32), name = 'b')
# b = tf.Variable(tf.zeros(2, dtype=tf.float32), name = 'b')  also works due to tf broadcasting
print(b)

x = tf.constant([[1.0,2.0,3.0]])
print(x)

<tf.Variable 'w:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.69048744,  0.6859552 ],
       [ 0.76124   , -0.8914021 ],
       [-0.39116696,  1.680041  ]], dtype=float32)>


<tf.Variable 'b:0' shape=(1, 2) dtype=float32, numpy=array([[0., 0.]], dtype=float32)>
tf.Tensor([[1. 2. 3.]], shape=(1, 3), dtype=float32)


In [5]:
with tf.GradientTape(persistent=True) as tape:
    y = x @ w + b  # @ is the sign for dot product
    loss = tf.reduce_mean(y**2)

In [6]:
[dl_dw, dl_db] = tape.gradient(loss, [w,b])
print(dl_dw)
print(dl_db)

tf.Tensor(
[[-0.3415083  3.943274 ]
 [-0.6830166  7.886548 ]
 [-1.0245249 11.829823 ]], shape=(3, 2), dtype=float32)
tf.Tensor([[-0.3415083  3.943274 ]], shape=(1, 2), dtype=float32)


# Dictionary Input



In [7]:
w = tf.Variable(tf.random.normal((3,2)), name = 'w')

x = tf.constant([[1.0,2.0,3.0]])

b = tf.Variable(tf.zeros((1,2)), name = 'b')

with tf.GradientTape(persistent=True) as tape:
    y = x @ w + b
    loss = tf.reduce_mean(y**2)

my_vars = {
    'w': w,
    'b': b
}

grad = tape.gradient(loss, my_vars)
print(grad['w'])
print(grad['b'])

tf.Tensor(
[[ 4.2240553 -1.0313644]
 [ 8.448111  -2.062729 ]
 [12.672166  -3.0940933]], shape=(3, 2), dtype=float32)
tf.Tensor([[ 4.2240553 -1.0313644]], shape=(1, 2), dtype=float32)


# Gradiens w.r.t a model

In [10]:
layer = tf.keras.layers.Dense(2, activation='relu')

x = tf.constant([[1.0,2.0,3.0]])

# Record
with tf.GradientTape() as tape:
    y = layer(x)
    loss = tf.reduce_mean(y**2)

grad = tape.gradient(loss, layer.trainable_variables)

print (grad)


[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.2071854, 0.       ],
       [2.4143708, 0.       ],
       [3.6215563, 0.       ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2071854, 0.       ], dtype=float32)>]


In [11]:
layer.trainable_variables


[<Variable path=dense_2/kernel, shape=(3, 2), dtype=float32, value=[[ 0.5852448   0.28751624]
  [ 0.2769928  -0.34969145]
  [ 0.02265167 -0.8031152 ]]>,
 <Variable path=dense_2/bias, shape=(2,), dtype=float32, value=[0. 0.]>]

In [12]:
type(layer.trainable_variables)

list